Repository openfga/sdk-generator, pull requests merged in 2022-09, with the labels that each got.

#25 chore(go-sdk): bump to 0.0.3
  .github/workflows/tests.yml
  Makefile
  config/clients/go/CHANGELOG.md.mustache
  config/clients/go/config.overrides.json
  config/clients/go/template/.github/workflows/main.yaml
  config/clients/go/template/go.mod.mustache
  config/clients/go/template/go.sum
Labels: Go SDK

#26 chore(all-sdks): update project introduction in README
  README.md
  config/common/files/README_project_introduction.mustache
Labels: documentation

#28 chore(dotnet-sdk): add changelog for v0.0.3
  config/clients/dotnet/CHANGELOG.md.mustache
  config/clients/dotnet/config.overrides.json
  config/clients/dotnet/template/Client_ApiClient.mustache
Labels: release

#22 feat: python SDK
  .github/workflows/tests.yml
  .gitignore
  Makefile
  README.md
  config/clients/python/.openapi-generator-ignore
  config/clients/python/CHANGELOG.md.mustache
  config/clients/python/config.overrides.json
  config/clients/python/generator.txt
  config/clients/python/patches/OpenFgaApi.md.patch
  config/clients/python/patches/open_fga_api.py.patch
  config/clients/python/template-source.json
  config/clients/python/template/.github/workflows/main.yaml
  config/clients/python/template/.snyk
  config/clients/python/template/README_api_endpoints.mustache
  config/clients/python/template/README_calling_api.mustache
  config/clients/python/template/README_common.mustache
  config/clients/python/template/README_initializing.mustache
  config/clients/python/template/README_installation.mustache
  config/clients/python/template/README_license_disclaimer.mustache
  config/clients/python/template/README_models.mustache
  config/clients/python/template/__init__.mustache
  config/clients/python/template/__init__api.mustache
  config/clients/python/template/__init__model.mustache
  config/clients/python/template/__init__package.mustache
  config/clients/python/template/api.mustache
  config/clients/python/template/api_client.mustache
  config/clients/python/template/api_doc.mustache
  config/clients/python/template/api_doc_example.mustache
  config/clients/python/template/api_test.mustache
  config/clients/python/template/asyncio/rest.mustache
  config/clients/python/template/configuration.mustache
  config/clients/python/template/credentials.mustache
  config/clients/python/template/credentials_test.mustache
  config/clients/python/template/exceptions.mustache
  config/clients/python/template/gitignore.mustache
  config/clients/python/template/model.mustache
  config/clients/python/template/model_doc.mustache
  config/clients/python/template/model_test.mustache
  config/clients/python/template/partial_header.mustache
  config/clients/python/template/python_doc_auth_partial.mustache
  config/clients/python/template/requirements.mustache
  config/clients/python/template/rest.mustache
  config/clients/python/template/setup.mustache
  config/clients/python/template/setup_cfg.mustache
  config/clients/python/template/test-requirements.mustache
  config/clients/python/template/tornado/rest.mustache
  config/clients/python/template/tox.mustache
Labels: Python SDK

#41 chore(js-sdk): bump deps
  config/clients/js/template/package-lock.mustache
  config/clients/js/template/package.mustache
Labels: JS/Node SDK

#42 release(js-sdk): update changelog for upcoming js-sdk release
  config/clients/js/CHANGELOG.md.mustache
  config/clients/js/config.overrides.json
Labels: JS/Node SDK
