Repository openfga/sdk-generator, pull requests merged in 2024-01, with the labels that each got.

#278 release(v0.3.4): with a fix for write model with conditions
  config/clients/go/CHANGELOG.md.mustache
  config/clients/go/config.overrides.json
  config/clients/go/template/client/client.mustache
  config/clients/go/template/client/client_test.mustache
  config/clients/go/template/example/example1/go.mod
  config/clients/go/template/example/example1/go.mod.mustache
  config/clients/go/template/example/example1/go.sum
  config/clients/go/template/go.mod.mustache
  config/clients/go/template/go.sum.mustache
Labels: release

#280 fix(go-sdk): dont escape HTML characters in conditions
  config/clients/go/template/model.mustache
  config/clients/go/template/model_simple.mustache
Labels: go-sdk

#291 chore(js-sdk): bump dependencies
  config/clients/js/template/package-lock.mustache
Labels: dependencies

#292 release(js-sdk): v0.3.1
  config/clients/js/CHANGELOG.md.mustache
  config/clients/js/config.overrides.json
Labels: js-sdk, release

#297 chore(python-sdk): enable PyPI trusted publishing
  config/clients/python/template/.github/workflows/main.yaml
Labels: python-sdk
